spring.application.name=Library-auth

## Spring Data
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PW}

## SQL
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.data-locations=classpath:/db/data.sql

## Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
api.redisconfig.secret=${REDIS_PW:123}

## Docker compose
spring.docker.compose.file=./compose.dev.yaml

##JWT
api.security.token.secret=${JWT_SECRET:my-secret-key}